{"name": "test_create_database_validation_error", "status": "passed", "description": "Verify that creating a database returns expected results", "attachments": [{"name": "log", "source": "69fb1d2d-4407-43c1-8e16-10d55473199f-attachment.txt", "type": "text/plain"}], "start": 1718901354387, "stop": 1718901354706, "uuid": "8835b199-aed9-47b9-b726-a5f35eb370a0", "historyId": "05badec5c51c7e7e486bfe93b7ea24bd", "testCaseId": "05badec5c51c7e7e486bfe93b7ea24bd", "fullName": "test_create_database#test_create_database_validation_error", "labels": [{"name": "parentSuite", "value": "databases"}, {"name": "severity", "value": "allure.severity_level.CRITICAL"}, {"name": "feature", "value": "databases"}, {"name": "suite", "value": "schemabased"}, {"name": "tag", "value": "schemabased"}, {"name": "host", "value": "Noutbuk-Dmitrij.local"}, {"name": "thread", "value": "27260-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_create_database"}]}